*Please read comments in the commits* - Final Steps for Project Completion - Bottom of the Page and Theory Of Inflation Work
jmontanholi/ProjectOneMicroverse pull request #4
Opened 2021-02-17 20:18 UTC by jmontanholi

## The Main Changes in this Pull Request Are:

- Aside Editor's Pick in the Middle Of the Text.

- Text Formatting and Margins

- Bottom Of the Page Extra Contents 

- Footer

### It was discussed with both Code Reviewers that in my Viewport Everything is in place (Pictures of it can be seen in one of the comments below)

2021-02-17 23:16 UTC, Temmarie requested changes
## Changes Required! :recycle:

### Hi @jmontanholi    ! :wave: :wave:

#### You have done well so far :clap: However, there are changes required for you to make in order for this project to be approved. Kindly work on them and submit them for another code review.

---

### **Recommended**

**General**
- [x] You have to write a descriptive Pull Request Message with a descriptive title as well. It's essential that your repository is professional, as this is one of the things that potential colleagues will look at when recruiting team members. Please refer to [pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243642/) for more information.

- [x] Your readme needs a bit of editing around the live link and author's sections. Check [here](https://www.markdownguide.org/cheat-sheet/) for how to use markdowns.

- [ ] I see you have a different font from that in the actual [NYT](https://www.nytimes.com/2014/03/18/science/space/detection-of-waves-in-space-buttresses-landmark-theory-of-big-bang.html?_r=0) site. Use [this](https://chrome.google.com/webstore/detail/font-picker/mmjbimgpcbaegjiieojddickpjbdkeej) chrome extension to solve this issue.

**Section Specific**
- [ ] Navigation bar
- The navbar elements to the left( the hamburger button, search button, space &cosmos) are a lot smaller than that of the actual site.

**Original** |  **Your clone**
------------ | -------------
![Screenshot (73)](https://user-images.githubusercontent.com/49621279/108278551-0f0fe180-7130-11eb-9a6d-374388c02c54.png) | ![Screenshot (74)](https://user-images.githubusercontent.com/49621279/108278708-41b9da00-7130-11eb-818d-fb233706c308.png)

- [ ] Main Content
- The theory of inflation: the images are bleeding into the texts and overlapping the navbar as well as shown below, please fix this.

**Original** |  **Your clone**
------------ | -------------
![Screenshot (76)](https://user-images.githubusercontent.com/49621279/108279192-0bc92580-7131-11eb-9656-374f6922115f.png) | ![Screenshot (75)](https://user-images.githubusercontent.com/49621279/108279241-256a6d00-7131-11eb-8854-8f991e1a63d8.png)

- The social media row at the base just before the More in Space and Astronomy section should have a larger size.
- Increase the width of the "More in Space and Astronomy" section, as well as the "Most Popular" section.
- The Editor's Picks is distorted. Please fix this.
- The footer needs a little bit of work done for it to be as similar as possible to the original.

**Original** |  **Your clone**
------------ | -------------                
![Screenshot (78)](https://user-images.githubusercontent.com/49621279/108280184-a8d88e00-7132-11eb-9939-135f8fd7563d.png) | ![Screenshot (79)](https://user-images.githubusercontent.com/49621279/108280261-c9a0e380-7132-11eb-9f14-7d574cfc22c4.png)
- For the above section, consider using [font awesome](https://fontawesome.com/v4.7.0/icons/) icons or [this](https://chrome.google.com/webstore/detail/svg-export/naeaaedieihlkmdajjefioajbbdbdjgp?hl=en-GB) chrome extension to get the icons used here.


__Kindly make the necessary changes and submit another code review request.__
_Feel free to reach me on slack for any inquiries about this review._ :wink:
__Grace Tamara Ekunola __
[GitHub](https://github.com/temmarie) | [LinkedIn](https://www.linkedin.com/in/ekunola-grace/) | [Twitter](https://twitter.com/TemmarieW)

2021-02-18 16:31 UTC, jmontanholi commented
Top Of Page:
![image](https://user-images.githubusercontent.com/73256642/108388277-3aa4d180-71ed-11eb-955b-577b65d8c5c1.png)
Main Text With Aside Editor's Pick:
![image](https://user-images.githubusercontent.com/73256642/108388350-4ee8ce80-71ed-11eb-8e68-d65c767a7995.png)
Theory Of Inflation without Nav Bar:
![image](https://user-images.githubusercontent.com/73256642/108388472-6fb12400-71ed-11eb-8f91-09ed14c0520c.png)
Theory Of Inflation with Nav Bar:
![image](https://user-images.githubusercontent.com/73256642/108388512-7c357c80-71ed-11eb-8d25-dc6621eb47a7.png)
Bottom Of Page Part 1:
![image](https://user-images.githubusercontent.com/73256642/108388584-8c4d5c00-71ed-11eb-8e3d-47778b700d63.png)
Bottom Of Page Part 2: 
![image](https://user-images.githubusercontent.com/73256642/108388651-9a9b7800-71ed-11eb-90b8-e2d2fe0bd6af.png)
Bottom Of Page Final:
![image](https://user-images.githubusercontent.com/73256642/108388690-a424e000-71ed-11eb-90e0-7bd0e786b6ad.png)

2021-02-18 20:14 UTC, teekaytech requested changes
## Status: Changes Required :warning: :vertical_traffic_light: 

### Hello @jmontanholi  :wave:

__You've made laudable progress so far. Most of the required changes have been fixed.
However, some changes are required before this project can be approved. Please check my comments below and fix them as appropriate.__

**[ REQUIRED CHANGES ]**

- [ ] As mentioned by the last reviewer, you still have some overlapping texts in your theory of inflation section of the main content. I will suggest you use CSS grid for this section to make things work better. Among other things, you can also consider reducing the font size.
- [ ] Also, you should consider reducing the left and right white spaces in the `More in Space and Astronomy` (left) and the `Most Popular` (right) sections. See the images below.

| Original Page | Your Clone |
| ------------------- | -------------- |
| ![org1](https://user-images.githubusercontent.com/26856491/108414179-34821580-722c-11eb-9757-b4af9035320c.png) | ![clone1](https://user-images.githubusercontent.com/26856491/108414281-54b1d480-722c-11eb-8eac-a3987ceaac3a.png) |
| ![original](https://user-images.githubusercontent.com/26856491/108415295-a60e9380-722d-11eb-87cd-c5104d8a3dcb.png) | ![clone](https://user-images.githubusercontent.com/26856491/108415231-8ecfa600-722d-11eb-8d2b-48882e5ec369.png) |


* * *
**Please make the required changes and submit another review request when you are done.**

* * *

**Taofeek Olalere
[Twitter](https://twitter.com/ola_lere) | [Github](https://github.com/teekaytech) | @taofeekolalere on Slack**
__Happy Coding :smiley:__

2021-02-18 22:29 UTC, wathigo requested changes
### CHANGES REQUIRED :o: 
Great job on this milestone.
#### REQUIRED
* We have a big embedded at Inflation Theory section of the page. See the comment :point_down: 

**After making the changes, submit another request for review.**

**Happy Coding :computer: 
Simon Wathigo**

2021-02-18 22:29 UTC, wathigo commented on index.html
> +                    <div class="inflationText t1">
**REQUIRED**
We should not embed a big screenshot to cover the Inflation theory concept. Embeding this screenshot is messing everything up.

Embedded Image   | The Result
:-------------------------|:-------------------------:
![Screenshot from 2021-02-18 17-16-23](https://user-images.githubusercontent.com/44072711/108429029-7780c080-720d-11eb-8ef6-9ace402254be.png) | ![Screenshot from 2021-02-18 17-02-02](https://user-images.githubusercontent.com/44072711/108428992-689a0e00-720d-11eb-868c-46118b34710c.png)

2021-02-18 22:33 UTC, jmontanholi commented on index.html
> +                    <div class="inflationText t1">
## Hello! First of all, thanks for the feedback.

Second, I don't really understand, this is exactly the way they do in the original page. And as you can see in the Pictures in My comment Above (As I said in the PR description) in my viewport you can see the Theory of inflation working fine(but as it is not a responsive project it can change depending on the viewport)

## Here is another screenshot so you can see:

![image](https://user-images.githubusercontent.com/73256642/108430436-1ca49480-7220-11eb-8db6-6d2459df0dd4.png)

2021-02-19 15:11 UTC, mikenath223 requested changes
### Hello  👋

**You've done pretty well here fixing a few issues raised in the previous review. 👌**

However, let's make a couple of changes.

- [ ] In the screenshot below in the theory of inflation section you'll notice that the images wrap into the texts kindly fix it. The images shouldn't wrap in the text. [Screenshot]👇
![ice_screenshot_20210219-160919](https://user-images.githubusercontent.com/33323077/108522461-26380600-72cd-11eb-82e6-828c23811547.png)


### **STATUS: CHANGES REQUESTED** 👷‍♂️

Kindly fix these issues and request another review👍
Feel free to contact me on slack(michgolden) if you need further clarification.

**HAPPY CODING 🎉💻🎉**

**Michgolden Ukeje (CR)**

2021-02-19 20:38 UTC, whiz25 approved these changes
## Approved ✅ 
Nice work on this PR. You managed to fix the requested changes. Which view port are you using? At first I could see the same problems with overlapping of text and images as the previous reviewers. I had to zoom out to `67%` to properly see every element on the page.

Anyways merge and proceed to the next project. Good luck.


### Martin Afani
Please merge and proceed to the next project.

2021-02-19 20:42 UTC, merged